Webbangame/GameStore/Controllers/GameStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webbangame.Models;

namespace Webbangame.Controllers
{
    public class GameStoreController : Controller
    {
        // tạo 1 đối tượng chứa toàn bộ dữ liệu database
           dbQLBangameDataContext data = new dbQLBangameDataContext();
        private List<GAME> laygamemoi(int count)
        {
            //sắp xếp 
            return data.GAMEs.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        // GET: GameStore
        public ActionResult Index()
        {
            //lấy 5 game mới 
            var game_moi = laygamemoi(5);
            return View(game_moi);
        }
        public ActionResult TheLoai()
        {
            var theloai = from tl in data.THE_LOAIs select tl;
            return PartialView(theloai);
        }
        public ActionResult NhaPhatTrien()
        {
            var nhaphattrien = from npt in data.NHA_PHAT_TRIENs select npt;
            return PartialView(nhaphattrien);

        }
        public ActionResult NhaPhatHanh()
        {
            var nhaphathanh = from nph in data.NHA_PHAT_HANHs select nph;
            return PartialView(nhaphathanh);
        }
        public ActionResult SPTheotheloai(string a)
        {
            var game = from g in data.GAMEs where g.MaTheLoai==a select g;
            return View(game);
        }
        public ActionResult SPTheonhaphathanh(int id)
        {
            
            var game = from s in data.GAMEs where s.MaNPH==id select s;
            return View(game);
        }
        public ActionResult SPTheonhaphattrien(int id)
        {
            var game = from g in data.GAMEs where g.MaNPT == id select g;
            return View(game);
        }
        public ActionResult Details(int id)
        {
            var game = from d in data.GAMEs
                       where d.MaGame == id
                       select d;
            return View(game.Single());
        }
        public ActionResult LienHe()
        {
            var lienhe = from lh in data.LIEN_HEs select lh;
            return PartialView(lienhe);
        }

    }

    
}

Webbangame/GameStore/Views/GameStore/Details.cshtml
<style type="text/css">
    #Datmua a{
        clear: both; background-color:red;
        color:white; width:120px; height:35px;
        display:block; float:right; text-align:center;
        padding-top:10px; text-decoration:none; front-weight:bold;
    }
    #Datmua a:hover{
        background-color:gray;
        color:red;

    }

</style>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Thông tin chi tiết game</h2>

<div>
    <div style="width:40%;float:left;border-left:dotted 1px;border-color:azure">
        <img src="~/Hinhsanpham/@Model.Anhbia"width="100%"/>
    </div>
    <div style="width:60%;float:left;padding:10px">
        <h4 style="font-weight:bold;color:red">Tên game: @Model.TenGame</h4>
        <p style="text-align:justify"><span style="font-weight:bold">Mô tả: </span>@Model.Mota</p>
        <p style="font-weight:bold"> Giá bán: <span style="color:red;font-size:16pt">@Model.GiaBan VND</span> </p>
    </div>
    <div>
            <div id="Datmua">
                <a href="@Url.Action("ThemGiohang","GioHang",new {@iMaGame=Model.MaGame,@strURL=Request.Url.ToString() })"class="list-group-item">Đặt Mua
                </a>

            </div>
    </div>
</div>

Webbangame/GameStore/Views/GameStore/Index.cshtml
@model IEnumerable<Webbangame.Models.GAME>

@{
    ViewBag.Title = "Index";

    Layout = "~/Views/Shared/_LayoutUser.cshtml";

}

<h2></h2>
<div>
    <p style="font-size:50px">đây là chỗ quảng cáo, mà quảng cáo gì thì chưa nghĩ ra</p>
</div>
<div style="margin-top:400px">
    @foreach (var game in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details", "GameStore", new { id = game.MaGame })">
                    <img alt="@game.TenGame" src="~/Hinhsanpham/@game.Anhbia" style="width:200px ;height:200px" class="cangiua" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @game.TenGame
                        </h4>
                        <p></p>


                    </div>
                    <div class="ratings">
                        <div class=>
                            <p class="pull-right">15 reviews</p>
                        </div>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>

                    </div>

            </div>
        </div>
    }
    </div>

   

Webbangame/GameStore/Views/GameStore/LienHe.cshtml
@model  IEnumerable<Webbangame.Models.LIEN_HE>
<p class="lead"></p>

    <div class="list-group">
        @foreach (var item in Model)
        {

             <a href="@Url.Action("ThongtinLH","GameStore")" class="list-group-item" >
                 <span class="glyphicon glyphicon-home"> </span>
                    @item.DC
                   
               <span class="glyphicon glyphicon-phone-alt"> </span>
               @item.SĐT
           </a>
               


        }
    </div>

Webbangame/GameStore/Views/GameStore/NhaPhatHanh.cshtml
@model  IEnumerable<Webbangame.Models.NHA_PHAT_HANH>
<p class="lead">Nhà Phát Hành Game</p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SPTheoNhaPhatHanh","GameStore",new {id=item.MaNPH })" class="list-group-item">
            @item.TenNPH
        </a>
    }  
</div>

Webbangame/GameStore/Views/GameStore/NhaPhatTrien.cshtml
@model IEnumerable<Webbangame.Models.NHA_PHAT_TRIEN>
<p class="lead">Nhà Phát Triển</p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SPTheonhaphattrien","GameStore",new { id = item.MaNPT })" class="list-group-item">
            @item.TenNPT
        </a>
    }
</div>

Webbangame/GameStore/Views/GameStore/SPTheonhaphathanh.cshtml
@model IEnumerable<Webbangame.Models.GAME>
@{
    ViewBag.Title = "SPTheoNPH";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h3 style="text-align:center;color:red">GAME THEO NPH</h3>
<div class="row">
    @foreach(var game in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details", "GameStore", new { id=game.MaGame })">
                <img alt="@game.TenGame" src="~/Hinhsanpham/@game.Anhbia" style="width:200px ;height:200px" class="cangiua" />
                <div>
                    <br />
                    <h4 style="text-align:center">
                        @game.TenGame
                    </h4>
                    <p></p>

                </div>
                <div class="ratings">
                    <div>
                        <p class="pull-right">15 reviews</p>
                    </div>
                    <p>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                        <span class="glyphicon glyphicon-star"></span>
                    </p>

                </div>
                    </a>

            </div>

       </div>
    }
</div>

Webbangame/GameStore/Views/GameStore/SPTheonhaphattrien.cshtml
@model IEnumerable<Webbangame.Models.GAME>
@{
    ViewBag.Title = "GAMETheoNPH";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center;color:red">GAME THEO NPT</h3>
<div class="row">
    @foreach (var game in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details", "GameStore", new { id=game.MaGame })">
                    <img alt="@game.TenGame" src="~/Hinhsanpham/@game.Anhbia" style="width:200px ;height:200px" class="cangiua" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @game.TenGame
                        </h4>
                        <p></p>


                    </div>
                    <div class="ratings">
                        <div>
                            <p class="pull-right">15 reviews</p>
                        </div>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>

                    </div>
                </a>
            </div>

        </div>
    }
</div>

Webbangame/GameStore/Views/GameStore/SPTheotheloai.cshtml
@model IEnumerable<Webbangame.Models.GAME>
@{
    ViewBag.Title = "SPTheotheloai";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center;color:red">GAME THEO THỂ LOẠI</h3>
<div class="row">
    @foreach (var game in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details", "GameStore", new { id= game.MaGame })">
                <img alt="@game.TenGame" src="~/Hinhsanpham/@game.Anhbia" style="width:200px ;height:200px" class="cangiua" />
                <div>
                        <br />
                        <h4 style="text-align:center">
                            @game.TenGame
                        </h4>
                        <p></p>

                    </div>
                    <div class="ratings">
                        <div>
                            <p class="pull-right">15 reviews</p>
                        </div>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>

                    </div>
                    </a>
            </div>
            
        </div>
    }
</div>

    

Webbangame/GameStore/Views/GameStore/TheLoai.cshtml
@model  IEnumerable<Webbangame.Models.THE_LOAI>
 <p class="lead">Thể loại Game</p>
 <div class="list-group">
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SPTheoTheLoai","GameStore",new {a=item.MaTheLoai })" class="list-group-item">
            @item.TenTheLoai
        </a>    
    }
</div>